changelog:
  categories:
    - title: "Added"
      labels:
        - "added"
    - title: "Changed"
      labels:
        - "changed"
    - title: "Removed"
      labels:
        - "removed"
    - title: "Fixed"
      labels:
        - "fixed"
    - title: "Documentation"
      labels:
        - "documentation"