# Name to appear in chat when responding to questions
bot-name: "Genius"

# Gemini options.
api-config:
  # Language model to use. See https://github.com/fletchly/genius/blob/main/supported-models.md for more info
  model-type: "gemini"
  # Credentials for the language model API
  api-key: ""
  # Base URL for the language model API endpoint
  base-url: ""
  # Response length (1 token ≈ 0.75 words on average).
  max-tokens: 400
  # Instructions for the AI model to follow when generating responses.
  system-context: "You are a helpful assistant for players in Minecraft. Your responses are concise. Do not use markdown syntax in your responses"