name: Genius
version: '0.0.0'
main: org.fletchly.genius.Genius
description: Generative AI integration for Minecraft servers.
author: fletchly
api-version: '1.21'

permissions:
  genius.use:
    description: "Allows the player to use the Genius plugin."
    default: notop
  genius.admin:
    description: "Allows the player to use Genius admin commands."
    default: op