@startuml
autonumber

actor Player
participant Command
participant ChatManager
participant ConversationService
participant OllamaService
participant OllamaClient
participant HttpClient



Player -> Command: "/genius <prompt>"
Command -> ChatManager: generateChat(prompt)
ChatManager -> ConversationService: getMessagesForPlayer()
ConversationService -->> ChatManager: context messages
ChatManager -> OllamaService: context messages + player message
OllamaService -> OllamaClient: fetchResponse(ollama request)
OllamaClient -> HttpClient: sendAsync(http request)

HttpClient -->> OllamaClient: http response
OllamaClient -->> OllamaService: ollama response
OllamaService -->> ChatManager: ollama message
ChatManager -->> ConversationService: appendConversation(message)
ChatManager -->> Command: response
Command -> Player: "[Genius] <response>"

@enduml